# Generated by Django 5.2.17 on 2026-10-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertical',
            name='accent',
            field=models.CharField(default='#0B7A75', max_length=7),
        ),
        migrations.AddField(
            model_name='vertical',
            name='accent_dark',
            field=models.CharField(default='#07403E', max_length=7),
        ),
        migrations.AddField(
            model_name='vertical',
            name='booking_noun',
            field=models.CharField(default='Appointment', max_length=30),
        ),
        migrations.AddField(
            model_name='vertical',
            name='booking_style',
            field=models.CharField(default='appointment', max_length=12),
        ),
        migrations.AddField(
            model_name='vertical',
            name='quick_prompts',
            field=models.CharField(blank=True, help_text='Comma separated chat shortcuts', max_length=500),
        ),
    ]
